name: initiial-pipeline-ci
on: 
  push:
    branches:
      - feature/setup-ci-pipeline
      - develop
      - main

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/Checkout@v4

      - name: setup-uv
        uses: astral-sh/setup-uv@v5
          with:
            python-version: "3.12"

      - name: Install dependencies
        run: uv pip install . --system
      
      - name: Run data script
        run: echo "python main.py"
